**ids-pdl04-hwk.ipynb**: This Jupyter notebook is provided by Joachim Vogt for the _Python Data Lab_ of the module _Introduction to Data Science_ offered in Fall 2022 at Jacobs University Bremen. Module instructors are Hilke Brockmann, Adalbert Wilhelm, and Joachim Vogt. Jupyter notebooks and other learning resources are available from a dedicated _module platform_.

# Homework assignments: NumPy basics

The homework assignments in this notebook supplement the tutorial *NumPy basics*.

- Solve the assignments according to the instructions.
- Upload the completed notebook to the module platform.
- Do not forget to enter your name in the markdown cell below.

The homework set carries a total of 20 points. Square brackets in the assignment titles specify individual point contributions.

## Name: Shayan Ali Khan

---
---

## Preparation

Import the NumPy module in the standard way (prefix `np`).

In [1]:
import numpy as np

On the module platform you find data files of the form `pdl04dat_SID.txt` where `SID` is a three-digit student ID. Each file contains three timeseries of synthetic temperature measurements, provided for demonstrating the assignment *Functions of NumPy arrays*.

- Identify the file `pdl04dat_SID.txt` with your personal student ID `SID`, then upload it to the working directory, i.e., the folder where this Jupyter notebook resides.
- The files `pdl04dat_100.txt` and `pdl04sol_100.txt` are provided to demonstrate the assignment. Upload the two files also to the working directory.

## Assignment: NumPy arrays from Python lists [3]

Complete the code cell below according to the instructions included as comments. In each case the resulting NumPy array and its `dtype` are to be displayed using the function `print()`.

In [3]:
### Consider the following one-dimensional NumPy array of integers
a01 = np.array(3*[3,5,7,11])
print('a01:',a01,a01.dtype)
### Create a copy a02 of a01 with the first and the second-last element changed to unity (integer 1).
a02 = np.copy(a01)
a02[0] = 1
a02[-2] = 1
print('a02:',a02,a02.dtype)
### Create a copy a03 of a01, then apply striding to reverse the sign of every third element of a04.
a03 = np.copy(a01)
a03 = a03[2::3] * -1
print('a03:',a03,a03.dtype)
### Using np.array(), create a copy a04 of a01 but with entries of type float64.
a04 = np.copy(a01)
a04 = a04.astype('float64')
print('a04:',a04,a04.dtype)

a01: [ 3  5  7 11  3  5  7 11  3  5  7 11] int32
a02: [ 1  5  7 11  3  5  7 11  3  5  1 11] int32
a03: [ -7  -5  -3 -11] int32
a04: [ 3.  5.  7. 11.  3.  5.  7. 11.  3.  5.  7. 11.] float64


## Assignment: Multi-dimensional arrays [3]

Complete the code cell below according to the instructions included as comments. In each case the resulting NumPy array is to be displayed using the function `print()`.

In [5]:
### Consider the following two-dimensional NumPy array of strings
a05 = np.array(list('abcdefghijklmno')).reshape(3,5)
print(a05)
### Create a copy a06 of a05 and change the entries 'd','i','n' to '1','2','3'
a06 = np.copy(a05)
a06[0,3] = '1'
a06[1,3] = '2'
a06[2,3] = '3'
print(a06)
### Create a copy a07 of a05 and change the entries 'g','h','i' to '4','5','6'
a07 = np.copy(a05)
a07[1,1] = '4'
a07[1,2] = '5'
a07[1,3] = '6'
print(a07)
### In a05, replace every second character of the alphabet with '7'.
a05 = a05.flatten()
a05[1::2] = '7'
a05 = a05.reshape(3,5)
print(a05)

[['a' 'b' 'c' 'd' 'e']
 ['f' 'g' 'h' 'i' 'j']
 ['k' 'l' 'm' 'n' 'o']]
[['a' 'b' 'c' '1' 'e']
 ['f' 'g' 'h' '2' 'j']
 ['k' 'l' 'm' '3' 'o']]
[['a' 'b' 'c' 'd' 'e']
 ['f' '4' '5' '6' 'j']
 ['k' 'l' 'm' 'n' 'o']]
[['a' '7' 'c' '7' 'e']
 ['7' 'g' '7' 'i' '7']
 ['k' '7' 'm' '7' 'o']]


## Assignment: Uniform NumPy arrays and range expressions [4]

Complete the code cell below according to the instructions included as comments. More specifically, replace the occurences of `42` with meaningful NumPy functions.

In [6]:
### Using np.full(), print a uniform NumPy array of shape (2,7) filled with the string 'Hi!'.
print(np.full((2,7),'Hi!'))
### Using np.ones(), print a uniform NumPy array of shape (3,5) filled with the float -999.9.
print(-1000.9+np.ones((3,5)))
### Using np.arange(), print the one-dimensional integer array [23,20,17,14,11] (in this order).
print(np.arange(23,10,-3))
### Using np.linspace(), print the one-dimensional floating-point array [-2.3,-1.9,-1.5,-1.1].
print(np.linspace(-2.3,-1.1,4))

[['Hi!' 'Hi!' 'Hi!' 'Hi!' 'Hi!' 'Hi!' 'Hi!']
 ['Hi!' 'Hi!' 'Hi!' 'Hi!' 'Hi!' 'Hi!' 'Hi!']]
[[-999.9 -999.9 -999.9 -999.9 -999.9]
 [-999.9 -999.9 -999.9 -999.9 -999.9]
 [-999.9 -999.9 -999.9 -999.9 -999.9]]
[23 20 17 14 11]
[-2.3 -1.9 -1.5 -1.1]


## Assignment: Array filtering using boolean masks [4]

Complete the code cell below according to the instructions included as comments. In each case the resulting NumPy array is to be displayed using the function `print()`.

In [7]:
### Consider the following two-dimensional array of integer random numbers in the interval [0,10].
a08 = -10 + np.random.randint(21,size=(3,5))
print(a08)
### Create a boolean mask indicating negative numbers.
mask1 = a08 < 0
print(mask1)
### Create a boolean mask indicating even numbers (hint: module operator %).
mask2 = a08 % 2 == 0
print(mask2)
### Create a boolean mask indicating negative even numbers.
mask3 = (a08 % 2 == 0) & (a08 < 0)
print(mask3)
### Replace negative even numbers with the integer 42.
a08[mask3] = 42
print(a08)

[[ -6  -1   4   6  10]
 [ -1  -9   7  -9   7]
 [ -3 -10   6   7   2]]
[[ True  True False False False]
 [ True  True False  True False]
 [ True  True False False False]]
[[ True False  True  True  True]
 [False False False False False]
 [False  True  True False  True]]
[[ True False False False False]
 [False False False False False]
 [False  True False False False]]
[[42 -1  4  6 10]
 [-1 -9  7 -9  7]
 [-3 42  6  7  2]]


## Assignment: Functions of NumPy arrays [6]

Consider the data files of the form `pdl04dat_SID.txt` where `SID` is a three-digit student ID. Each file contains timeseries of synthetic temperature measurements over one year at three stations A, B, and C in the second, third, and fourth column (column indices 1,2,3), respectively. The first column (index 0) contains a day counter.

Complete the code cell below according to the instructions included as comments. More specifically, replace the occurences of `42` with meaningful NumPy functions.

- *Mean values of indiviual columms*: these are the annual means for the three stations A, B, C.
- *Number of maxima within columns*: for each station X, this is the number of days when the temperature measured at X is the largest of all three stations. Hint: NumPy functions `argmax()` and `sum()`.
- *Number of minima within columns*: for each station X, this is the number of days when the temperature measured at X is the smallest of all three stations. Hint: NumPy functions `argmin()` and `sum()`.

In [18]:
### Test the code with SID=100, then use your personal student ID for the final run of the notebook.
SID = 244
### Store all four columns of the file pdl04dat_SID.txt in the two-dimensional array data.
data = np.genfromtxt('pdl04dat_'+str(SID)+'.txt',skip_header=1)
### Remove the first column of the two-dimensional array data.
data = data[:,1:]
### Print: student ID and empty line.
print('\n')
print('Student-ID: {}'.format(SID))
print('\n')
#.. Print: mean values of individual columns.
print('Station A, annual mean: {:7.3f}'.format(data.mean(axis = 0)[0]))
print('Station B, annual mean: {:7.3f}'.format(data.mean(axis = 0)[1]))
print('Station C, annual mean: {:7.3f}'.format(data.mean(axis = 0)[2]))
print('\n')
#.. Print: number of maxima within columns.
print('Station A, number of maxima: {:3d}'.format(np.sum(np.argmax(data, axis = 1) == 0)))
print('Station B, number of maxima: {:3d}'.format(np.sum(np.argmax(data, axis = 1) == 1)))
print('Station C, number of maxima: {:3d}'.format(np.sum(np.argmax(data, axis = 1) == 2)))
print('\n')
#.. Print: number of minima within columns.
print('Station A, number of minima: {:3d}'.format(np.sum(np.argmin(data, axis = 1) == 0)))
print('Station B, number of minima: {:3d}'.format(np.sum(np.argmin(data, axis = 1) == 1)))
print('Station C, number of minima: {:3d}'.format(np.sum(np.argmin(data, axis = 1) == 2)))
print('\n')



Student-ID: 244


Station A, annual mean: 289.939
Station B, annual mean: 289.730
Station C, annual mean: 290.054


Station A, number of maxima: 135
Station B, number of maxima:  92
Station C, number of maxima: 138


Station A, number of minima: 129
Station B, number of minima: 101
Station C, number of minima: 135




Here is the output that you should obtain for `SID = 100`, i.e., for the sample data file `pdl04dat_100.txt`.

In [16]:
f = open('pdl04sol_100.txt','r')
smpout = f.read()
f.close()
print(smpout)


Student-ID: 100

Station A, annual mean: 290.611
Station B, annual mean: 290.326
Station C, annual mean: 290.764

Station A, number of maxima: 135
Station B, number of maxima:  92
Station C, number of maxima: 138

Station A, number of minima: 131
Station B, number of minima: 108
Station C, number of minima: 126




---
---